# Generated by Django 2.1.7 on 2019-04-15 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mton', '0004_auto_20190411_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
