# Generated by Django 2.1.7 on 2019-04-22 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20190422_1650'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hashtag',
            options={'ordering': ['content']},
        ),
        migrations.RemoveField(
            model_name='hashtag',
            name='n_user',
        ),
    ]
